# Generated by Django 5.0 on 2024-02-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donar',
            name='region',
            field=models.CharField(choices=[('INDIA', 'INDIA'), ('Othercountry', 'Othercountry')], max_length=100),
        ),
    ]
