# Generated by Django 5.0.2 on 2024-02-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0003_alter_donar_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('NGO', 'NGO'), ('ORPHANAGE', 'ORPHANAGE'), ('OLDAGEHOME', 'OLDAGEHOME')], max_length=100),
        ),
    ]
