# Generated by Django 5.0.2 on 2024-02-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0004_alter_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('mappingid', models.AutoField(primary_key=True, serialize=False)),
                ('donar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.donar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.user')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
