# Generated by Django 5.0.2 on 2024-02-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0005_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donar',
            name='donarid',
        ),
        migrations.AlterField(
            model_name='donar',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
