# Generated by Django 5.2 on 2025-04-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0007_donations_usercontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donations',
            new_name='Donation',
        ),
        migrations.AlterModelTable(
            name='donation',
            table='donation',
        ),
    ]
